/**
 * Master lease agreement text, adapted from the Sermony Properties
 * "Memorandum of Agreement of Lease" template. Paragraphs are rendered in
 * order by lease-pdf.helper.ts. {{TOKEN}} placeholders are substituted
 * with real tenancy data at generation time - anything left as literal
 * dots/blanks in this file (e.g. the signature block) is meant to stay
 * blank on the printed page for wet-ink signing.
 *
 * "heading" paragraphs are rendered bold/centered (document title,
 * "Witnesseth", the two-party names). Everything else is a regular
 * left-aligned paragraph, spaced with a blank line after it.
 */

export interface LeaseParagraph {
  text: string;
  heading?: boolean;
}

export const LEASE_TEMPLATE_PARAGRAPHS: LeaseParagraph[] = [
  { text: 'MEMORANDUM OF AGREEMENT OF LEASE', heading: true },
  { text: 'Made and entered into by and between' },
  { text: '{{LESSOR}}', heading: true },
  { text: '(Hereinafter referred to as "the Lessor")' },
  { text: '&' },
  { text: '{{LESSEE}}', heading: true },
  { text: 'D.O.B: {{DOB}}' },
  { text: 'ID No: {{ID_NUMBER}}' },
  { text: 'EMAIL: {{EMAIL}}' },
  { text: 'Cell Number: {{PHONE}}' },
  { text: '(Hereinafter styled the Lessee of the other part)' },
  { text: 'Witnesseth', heading: true },
  { text: 'FIRST: The Lessor hereby lets to the Lessee who hereby hires from the Lessor' },
  { text: 'ADDRESS: {{ADDRESS}}' },
  { text: '(Hereinafter styled the Leased Premises)' },
  { text: 'SECOND: The Lease shall commence on the {{LEASE_START}} and shall continue to run for a period of {{DURATION}} up to {{LEASE_END}}. Lease renewal fee (15% of your rent) shall be paid upon every lease expiry.' },
  { text: 'THIRD: The rent for the use and occupation of the said premises is US${{RENT}} (.................................................... United States Dollars), plus payment of city of Harare council bill as levied by the council monthly. The receipt shall be brought together with the rent every month. (failure to produce city of Harare receipt/levy will lead to that certain amount being deducted from rent), payable in advance directly to {{ACCOUNT_NAME}} by the FIRST OF EACH AND EVERY MONTH. THE RENT MAY BE REVIEWED FROM TIME TO TIME BY MUTUAL CONSENT.' },
  { text: 'FOURTH: In the event of the present tenant not having vacated the premises by the N/A or should the Lessor be unable to give the Lessee possession on the date there in before stipulated for any reason whatsoever then the Lessee shall have no claim for damages or any right of action whatsoever against the Lessor and/or the agents by reason of the fact the Lessee was unable to obtain possession of the premises on the specified date.' },
  { text: 'FIFTH: The lessee shall only use the premises for {{USE_TYPE}}.' },
  { text: 'SIXTH: At the conclusion of the above-mentioned term and in the absence of any specific provision to the contrary hereinafter provided in this Agreement, unless notice has been given in writing by either party at least one calendar months before such conclusion, the occupation of the said premises will be continued subject to one calendar month notice on either side being in writing.' },
  { text: "SEVENTH: The Lessee agrees to maintain the leased premises in a good state of decoration and repair except for defects reported to Lessor or Lessor's Agent in accordance with the tenth clause of this Agreement of the lease. The lessee to deposit with the Lessor or Lessor's Agent the sum of US${{DEPOSIT}} (.................................................... United States Dollars) this amount or portion thereof to become forfeit up to the amount of damages caused to the property during the tenancy or to cover any loss sustained by the Lessor or Lessor's agent including loss of rental, provided that this sum shall be refunded to the Lessee within 21 days of the Lessee vacating the premises if the Lessee shall have performed all his/her obligations." },
  { text: 'EIGHTH: The Lessee shall pay city council bill, levy and electricity consumed upon the Leased Premises.' },
  { text: 'NINTH: The Lessee agrees to vacate the leased premises by not later than 12 noon on the last day of the month as referred to in Clause 6.' },
  { text: 'TENTH: The Lessee hereby acknowledge that the said premises and buildings including any mechanical or electrical equipment attached to or operating from wells, boreholes, or other water supplies, or mechanical or electrical equipment for the supply of electric current are in good state of repair and condition, and that all keys, locks glass windows, electrical installations and other appurtenances of the said premises are like in good order and condition, with the exceptions noted in writing, and the Lessee hereby promises and undertakes to keep and maintain the inside of the premises in good state of decoration and repair and in a clean and sanitary condition during the currency of this Agreement, and to replace when necessary washers on taps, electric light and power fuses and electric bulbs. The Lessee will also maintain the electric water heaters and replace if necessary defective thermostats and elements contained therein. At the termination of the Lease, the Lessee agrees to return and redeliver the said premises to Lessor in like good state of decoration and repair, fair wear and tear alone excepted, and to make good and repair at his own cost and charge any damage or breakage and to replace any missing or broken articles, glass, locks, keys, taps, etc. The Lessee will repair any damages rising out of burglary, forced entry or attempted forced entry.' },
  { text: "The Lessee agrees to inform The Lessor's Agent in writing of any damage to the interior decorations and any other repairs necessary to the premises within seventy-two hours of taking occupation." },
  { text: 'Should no complaint be received within the specified time, the Lessee agrees full responsibility for the good state of the interior decoration, repairs and replacement as herein before detailed.' },
  { text: 'ELEVENTH: The Lessor shall keep all main walls and roof in order but shall not be responsible for any defects therein or damage done to articles or injury to the Lessee and any occupant of the said premises. It shall be the duty of Lessee to acquaint the Lessor with any defects in the said walls and roofs as soon as defects come to the knowledge of the Lessee.' },
  { text: "TWELVETH: The Lessor and/or Agents shall not be liable to the Lessee for any injury of any description which the Lessee's family, or any employee or servant any relative, friend, acquaintance, visitor, invitee or guest of the Lessee may sustain directly or indirectly in or about the leased premises or in or about the garage or storerooms or servant's room on in or about any part of the building in which the Leased premises or in the building in which the leased premises are situated, or any act done or any neglect on the part of the Lessor or any of the Lessor's employee, servants or agents against, any claim by any injury loss or damage to any such person." },
  { text: 'THIRTEENTH: The Lessor shall be responsible for the insurance of the leased premises loss or damage by fire but shall not do or cause to be any act, matter or thing whereby the insurance rate in respect of the leased premises shall be increased or the rights of the policyholder in any way be prejudiced.' },
  { text: "FOURTEENTH: The Lessee shall not make any external or internal alterations or additions to said premises whether structural or otherwise without the written consent of the Lessor, and any alterations or improvements that may be authorized shall become the sole property of the Lessor and shall not be removed from the premises at the termination of the Lessee's tenancy. The Lessee shall not interfere with the present electrical installation in the said premises or affix any electrical lamps, other than those approved by the lessor; or drive or permit to be driven any nails or screws into the walls or ceilings of the said premises in such a manner as may damage or disfigure the walls or any portion of the premises; or harbour or permit the storage or harbouring of any article, or do any act, matter or things as may be calculated to increase the rate of fire insurance of the said building, or whereby the same may be rendered void or endangered; or write, affix, erect or permit to be written, affixed, or erected any sign, signboard writing fixtures, fitting or other erection on the exterior of the premises without the written consent of the Lessor; and Lessee shall be liable for damage done to the building aforesaid or any part thereof by reason of his moving any furniture or other articles to or from the premises hereby let." },
  { text: 'FIFTEENTH: The Lessee shall not contravene or permit any contravention of the laws and regulations of the Township Company, Municipality, Town Board or Government or the conditions of the title under which the properties are held by the Lessor, and shall all times confirm to the same.' },
  { text: "SIXTEENTH: The Lessee shall not keep or permit any live animals to be kept on the leased premises, save with the Lessor's consent." },
  { text: 'SEVENTEENTH: The Lessee shall not hang any washing, linen or blankets on the outside of the premises or in a position where the same may cause the building and the surrounding areas to look unsightly and/or untidy.' },
  { text: 'EIGHTEENTH: The Lessee shall not cause or allow any nuisance of any description whatsoever to be done to neighbours.' },
  { text: "NINETEENTH: Should the drain connecting the premises with the main sewers be blocked, and should the blockage be above the portion of the drain which serves the said premises with the council's main sewer, or with any other private sewer conveying sewerage from other premises, the Lessee shall have it cleared, and should he neglect to do this the; lessor or his Agent shall have the work done and the Lessee hereby undertakes to refund to him the cost thereof. Should the premises be connected to the septic tanks, the Lessee accepts full responsibility for maintaining the drains leading to the tanks and keeping the septic connected to the toilets, provided there is not negligence on the part of the Lessee." },
  { text: "TWENTIETH: The Lessee agrees to keep and maintain the gardens and grounds in a neat and tidy condition free from weeds and shall not cut down any trees, hedges or shrubs except by way of normal pruning during the said Lessee's tenancy, and at all the termination thereof shall not remove any trees, shrubs, hedges, plants, fencing etc. or any other improvements that may have been carried out by the Lessee or Lessor to the said garden during the period of occupation by the Lessee. The Lessee further undertakes in keeping the lawns surrounding the leased premises in a neat and tidy condition and shall for this purpose ensure that such lawns are regularly mowed and adequate fertilizer placed thereon." },
  { text: 'TWENTY FIRST: The Lessee shall be responsible for the timeous fumigation of pets to the interior of the property, cockroaches, ticks, fleas, rodents, silver fish, bed bugs and sugar ants and any other similarly related nuisances, should they be caused by neglect on the Lessee in keeping the property in a clean and sanitary conditions or due to animals or birds or poultry being kept on the premises. Furthermore, if the pets should become prevalent within two weeks of vacating the premises by the Lessee, he shall still be responsible for any costs incurred in fumigating. The Lessor shall be responsible for the prompt fumigation of any white, black or red ants or termites connected to the exterior of the property or any woodwork in the premises.' },
  { text: 'TWENTY SECOND: The Lessor or his Agent shall be entitled at all reasonable times to enter upon the said premises to see the condition thereof, and with his workmen, agents and others to execute such repairs to the said premises, both external and internal shall be compatible with the proper repair and upkeep of the said premises.' },
  { text: 'TWENTY THIRD: The Lessee shall not have the right to assign his interests in the Lease nor to sublet the premises or any portion thereof, nor shall the Lessee part with possession of, or suffer, permit or allow any other person the use of or occupation of the premises or any portion thereof, without the written consent of the Lessor first had and obtained, which consent shall be at the absolute discretion of the Lessor but shall not be unreasonably withheld. Inter alia, any association by the Lessee with any other person whereby the latter is admitted into the partnership (whether disclosed, anonymous or otherwise) or engaged by the Lessee on a profit sharing basis, shall be deemed to be a permission by the Lessee of the use or occupation by another person of the premises in terms of the foregoing.' },
  { text: "TWENTY FOURTH: The Lessor shall have the right of affixing and exhibiting on the said premises 'To let' or 'For Sale' notices and the Lessee shall permit prospective tenants or buyers to view the interior of the premises during reasonable hours." },
  { text: 'TWENTY FIFTH: No agreement at variance with the terms and conditions of this agreement shall be binding on the parties unless confirmed in writing by the parties hereto, and any indulgence which the Lessor may show to the Lessee, and more particularly, any act of the Lessor in accepting any payments after due date or in accepting a lesser sum than the amount due, shall not in any way prejudice his right or be construed as a waiver of the same by the Lessor.' },
  { text: "TWENTY SIXTH: Should the Lessee fail to pay the monthly rental within 7 (seven) days of its due date, or commit any breach of any conditions or clauses of this agreement, the Lessor or his Agent shall have the right at once to cancel and put an end to his lease or re-enter and take immediate possession of the said premises, without prejudice to the Lessor's right to claim unpaid rent and damages and the Lessor without prejudice to the foregoing shall in action for the possession the premises entitled to claim the rent for the month in which the action is instituted as and by way of liquidated damages. No laxity temporary or otherwise of any provision of this Agreement shall be taken by the Lessee's precedent or justification for continuing the same and the waiver at any time by the Lessor of his rights in respect of any past breach shall not in any way prejudice his rights in regard to any other monies due in terms of this Agreement or of the non-compliance with any of the provisions, the latter shall in either of such events be responsible for, and shall on demand pay all legal costs and disbursements so incurred, including particularly collection charges and costs as between attorney and client." },
  { text: "TWENTY SEVENTH: The Lessee hereby declares to choose domicillium at executandi for all purpose under this Lease at the demised premises, where all legal notices and legal processes in relation to this Agreement may be effectually delivered and served. The further consents hereby to jurisdiction of the Magistrate's court or the High Court whichever the Lessor elects in respect of any proceedings instituted by the Lessor arising from any dispute to the Lease Agreement." },
  { text: "TWENTY EIGHTH: The cost of preparing this Lease Agreement and the attendance's fees incidental thereto shall be borne by the Lessee." },
  { text: "TWENTY NINTH: Should the Lessor's rates, mortgage bond repayments, insurance or levy payments levied in respect of the leased premises be increased during the currency of this Lease or any renewal thereof, then the rental payable per month by the Lessee shall be increased by an amount proportionate to such increase." },
  { text: 'THIRTIETH: The Lessee acknowledge that a swimming pool is erected upon the leased premises and undertakes to keep the said swimming pool filled with water and in good order and condition and to ensure that the water is kept bright and clean by regular application of Alginate and other additives as instructed by the Lessor. The Lessee further undertakes to have the filtration plant and equipment serviced at least once during the currency of this Lease, or once a year, whichever is the lesser.' },
  { text: 'THIRTY FIRST: In terms of the lease agreement drawn up between the above parties the monthly rent is payable without demand on or before the first day of each and every month. It is further agreed that should the Lessee pay the rent due for any particular month after the seventh day of that month then a penalty interest charge shalt apply. The interest penalty charge shall be 20% of the monthly rent. In the event that the rent remains unpaid after the expiry of the month in which it was due then a further interest charge of 20% of the monthly rent shall apply to each and every further month that the rent remains outstanding after the first day of each month. It is particularly recorded that the penalty interest is payable in full for each month that the rent remains unpaid after the date stipulated above, regardless of the date of which the rent was actually paid. The penalty interest charge is due on demand and it is agreed that failure, pay the same constitutes a breach of the Lease Agreement, and that the remedies available to the Lessor in the event of non payment of interest due are the same as those applicable in the event of non payment of penalty rent due are the same as those applicable in the event of non or late payment of rent as contained in the Lease Agreement. Lessee acknowledges that the excess is in respect of interest on late payment and wasted costs.' },
  { text: 'THIRTY SECOND: The Lessee agrees that the deposit, which must be paid prior to occupation, will be used to pay for the repairs of any damages caused by the Lessee. Under no circumstances shall the Lessee deduct any amount from such deposit for any rents to the Lessor on termination of the Lease unless otherwise agreed in writing.' },
  { text: 'THIRTY THIRD: The monthly levy payable by the Lessee shall be paid in full by the lessee should this amount increase at any time during the period of this Lease agreement, it is mutually agreed that the Lessee will pay the total amount.' },
  { text: "THIRTY FOURTH: The Lessor agrees to pay Agent's commission/fees at tariff rate in respect of this Letting, such commission to be deducted monthly by {{ACCOUNT_NAME}} for the full period of this Lease and for any additional period thereafter that the tenant introduced by the Agent, remains in occupation of the said premises even if the Lessor terminates this management or collection mandate before the expiry of the contract." },
  { text: 'THIRTY FIFTH: The Lessor further agrees that should the Lessee introduced by {{ACCOUNT_NAME}} wish to purchase the premises hereby leased at any time during this or tenancy thereafter, then in such event the sale shall be conducted by {{ACCOUNT_NAME}} which sale the Lessor acknowledges arises from {{ACCOUNT_NAME}} introduction shall be entitled to commission at tariff from the Lessor.' },
  { text: 'For the due and faithful performance and fulfillment of this Lease, and every part thereof we, the parties thereto do hereby bind our persons and property of every description according to law.' },
  { text: 'IN WITNESS WHERE OF we have hereunto set our hands at {{SIGNING_CITY}}, in the presence of the undersigned witness.' },
  { text: 'Thus done and signed this ............ day of .................................... at ....................' },
  { text: 'LESSEE .......................................................          LESSOR ......................................................' },
  { text: 'AS WITNESS .................................................          AS WITNESS ................................................' },
  { text: 'DATE ...........................................................          DATE ........................................................' },
  { text: '....................................................' },
  { text: 'FOR {{ACCOUNT_NAME}}', heading: true },
];

/** Substitutes {{TOKEN}} placeholders in every paragraph with real values. */
export function fillLeaseTemplate(tokens: Record<string, string>): LeaseParagraph[] {
  return LEASE_TEMPLATE_PARAGRAPHS.map((p) => ({
    ...p,
    text: p.text.replace(/\{\{(\w+)\}\}/g, (_, key) => tokens[key] ?? ''),
  }));
}
